--[[--------------------------------------------------------------------
	Hydra
	Multibox leveling helper.
	Copyright (c) 2010-2015 Phanx <addons@phanx.net>. All rights reserved.
	http://www.wowinterface.com/downloads/info17572-Hydra.html
	http://www.curse.com/addons/wow/hydra
	https://github.com/Phanx/Hydra
----------------------------------------------------------------------]]

local HYDRA, Hydra = ...
local L = setmetatable({}, { __index = function(t, k)
	if k == nil then return "" end
	local v = tostring(k)
	rawset(t, k, v)
	return v
end })
Hydra.L = L

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED. SEE:
-- http://wow.curseforge.com/addons/hydra/localization/

------------------------------------------------------------------------
-- English
------------------------------------------------------------------------

L.Hydra_Notes = "Multiboxing and group leveling helper."
L.Assist/Assist = "Assist"
L.Assist/AssistFailed = "%s could not assist you due to an unknown error."
L.Assist/AssistFailedCombat = "%s will assist you after combat."
L.Assist/AssistFailedTrust = "%s cannot assist you because you are not on their trusted list."
L.Assist/AssistGetMacro = "Get Macro"
L.Assist/AssistGetMacro_Info = "If you prefer to activate the Assist function from your action bars, you can use this button to get a macro you can drop onto any action button."
L.Assist/AssistHelpText = "This module is really only useful in combination with key cloning software. You should set your selected |cffffffffAssist|r key to be sent to your secondary clients."
L.Assist/Assist_Info = "Synchronizes an assist target across trusted group members."
L.Assist/AssistMacro = "Assist"
L.Assist/AssistMacro_Info = "Set a key binding to assist your current assist target."
L.Assist/AssistRespond = "Assist"
L.Assist/AssistRespond_Info = "Respond to assist requests from trusted group members."
L.Assist/AssistSet = "%s will now assist you."
L.Assist/AssistUnset = "%s is now assisting %s instead of you."
L.Assist/NobodyAssisting = "Nobody is currently assisting you."
L.Assist/RequestAssist = "Request Assist"
L.Assist/RequestAssist_Info = "Set a key binding to request that all group members set you as their assist target."
L.Assist/SlashAssistMe = "/assistme"
L.Automation/AcceptCombatRes = "Accept combat resurrections"
L.Automation/AcceptCombatRes_Info = "Accept resurrections in combat from all group members."
L.Automation/AcceptedRes = "Accepted a resurrection from %s."
L.Automation/AcceptedSummon = "Accepting a summon from %1$s to %2$s."
L.Automation/AcceptedSummonCombat = "Accepting a summon when combat ends..."
L.Automation/AcceptRes = "Accept resurrections"
L.Automation/AcceptRes_Info = "Accept resurrections out of combat from all group members."
L.Automation/AcceptSummons = "Accept summons"
L.Automation/AcceptSummons_Info = "Accept summons from trusted players."
L.Automation/Automation = "Automation"
L.Automation/AutomationHelpText = ""
L.Automation/Automation_Info = "Automates simple repetetive tasks, such as clicking common dialogs."
L.Automation/DeclineArenas = "Decline arena teams"
L.Automation/DeclineArenas_Info = "Decline arena team invitations and petitions from all players."
L.Automation/DeclinedArena = "Declined an arena team invitation from %s."
L.Automation/DeclinedArenaPetition = "Declined an arena team petition from %s."
L.Automation/DeclinedDuel = "Declined a duel request from %s."
L.Automation/DeclinedGuild = "Declined a guild invitation from %s."
L.Automation/DeclinedGuildPetition = "Declined a guild petition from %s."
L.Automation/DeclineDuels = "Decline duels"
L.Automation/DeclineDuels_Info = "Decline duel requests from all players."
L.Automation/DeclineGuilds = "Decline guilds"
L.Automation/DeclineGuilds_Info = "Decline guild invitations and petitions from all players."
L.Automation/NoRepairMoney = "Insufficient funds to repair!"
L.Automation/NoRepairMoneyGuild = "Insufficient guild bank funds to repair!"
L.Automation/Repair = "Repair equipment"
L.Automation/Repaired = "Repaired all items for %s."
L.Automation/RepairedGuild = "Repaired all items with guild bank funds for %s."
L.Automation/RepairGuild = "Use guild funds"
L.Automation/RepairGuild_Info = "Pay for repairs out of the guild bank when possible."
L.Automation/Repair_Info = "Repair all equipment when interacting with a repair vendor."
L.Automation/SellJunk = "Sell junk"
L.Automation/SellJunk_Info = "Sell junk (gray) items when interacting with a vendor."
L.Automation/SoldJunk = "Sold %1$d junk |4item:items; for %2$s."
L.Automation/SummonExpired = "Summon expired!"
L.Chat/AppFocus = "Application focus"
L.Chat/Chat = "Chat"
L.Chat/ChatHelpText = [=[Type a message in group chat to reply to the last forwarded whisper from any character.

Type "|cffffffff@name Your message here|r" in group chat to reply to the last forwarded whisper from the character "name".

Type "|cffffffff@name Your message here|r" in a whisper to a character to direct that character to send the message as a whisper to "name".]=]
L.Chat/Chat_Info = "Forwards whispers sent to inactive characters to group chat, and forwards replies to the original sender."
L.Chat/DetectionMethod = "Detection method"
L.Chat/DetectionMethod_Info = [=[Select the method to use for detecting the primary character.

If you are multiboxing on multiple physical machines, or are running multiple copies of WoW in windowed mode, the "Application Focus" mode will probably not work for you, and you should make sure that your primary character is the group leader.]=]
L.Chat/GroupLeader = "Group leader"
L.Chat/GroupTimeoutError = "Group chat forwarding timeout reached."
L.Chat/GroupTimeout_Info = "If this many seconds have elapsed since the last forwarded message, don't forward messages typed in group chat to the last whisperer unless the target is explicitly specified."
L.Chat/WhisperFrom = "%1$s received a whisper from %2$s."
L.Chat/WhisperFromBnet = [=[%1$s received a Battle.net whisper from %2$s:
%3$s]=]
L.Chat/WhisperFromConvo = [=[%1$s received a Battle.net message from %2$s:
%3$s]=]
L.Chat/WhisperFromGM = "%s has received a whisper from a GM!"
L.Chat/WhisperTimeoutError = "Whisper timeout reached."
L.Core/AddedTrusted = "%s has been added to your trusted list."
L.Core/AddGroup = "Add Group"
L.Core/AddGroup_Info = "Add everyone in your current group to your trusted list."
L.Core/AddName = "Add a name"
L.Core/AddName_Info = "Add a name to your trusted list."
L.Core/ClickForOptions = "Click for options."
L.Core/CoreHelpText = [=[Hydra operates on the basis of "trust". You tell it which characters you trust, whether they're your multibox characters or just your questing buddies, and features are enabled or disabled depending on whether you're in a group with trusted characters or not.

For example, whispers are only forwarded to group chat if everyone in the group is on your trusted list.]=]
L.Core/Enable_Info = "Enable this module."
L.Core/Hydra_Info = "Hydra is a multiboxing and group leveling helper that aims to minimize the need to actively control secondary characters."
L.Core/RemoveAll = "Remove All"
L.Core/RemoveAll_Info = "Clear your existing trusted list, removing all characters from all servers."
L.Core/RemovedTrusted = "%s has been removed from your trusted list."
L.Core/RemoveName = "Remove a name"
L.Core/RemoveName_Info = "Remove a name from your trusted list."
L.Core/Timeout = "Timeout"
L.Core/Verbose = "Verbose"
L.Core/Verbose_Info = "Enable notification messages from this module."
L.Debug/Debug = "Debug"
L.Debug/DebugCore = "Core"
L.Debug/Debug_Info = "Enable debugging messages for the selected parts of Hydra."
L.Follow/AcceptCorpse = "Resurrect to corpse"
L.Follow/AcceptCorpse_Info = "Set a key binding to direct dead group members to accept resurrection to their corpse."
L.Follow/CanReincarnate = "%s can use Reincarnation."
L.Follow/CanSelfRes = "%s can self-ressurect."
L.Follow/CantRes = "%s cannot be resurrected!"
L.Follow/CantResDelay = "%1$s cannot be resurrected for %2$d more seconds!"
L.Follow/CanUseSoulstone = "%s can use a Soulstone."
L.Follow/CmdAccept = "ac?c?e?p?t?"
L.Follow/CmdRelease = "re?l?e?a?s?e?"
L.Follow/Follow = "Follow"
L.Follow/FollowHelpText = [=[Type "|cffffffff/followme|r" to direct nearby group members to follow you.

Type "|cffffffff/corpse release|r" to direct dead group members to release their spirits.

Type "|cffffffff/corpse accept|r" to direct dead group members to accept resurrection to their corpse.]=]
L.Follow/Follow_Info = "Responds to follow requests from trusted group members."
L.Follow/FollowingYouStart = "%s is now following you."
L.Follow/FollowingYouStop = "%s is no longer following you."
L.Follow/FollowMe = "Request follow"
L.Follow/FollowMe_Info = "Set a key binding to direct nearby group members to follow you."
L.Follow/FollowTarget = "Follow target"
L.Follow/FollowTarget_Info = "Set a key binding to follow your current target."
L.Follow/FollowTooFar = "%s is too far away to follow!"
L.Follow/RefollowAfterCombat = "Refollow after combat"
L.Follow/RefollowAfterCombat_Info = "Automatically try to follow your last followed target when leaving combat."
L.Follow/Reincarnate = "Reincarnate"
L.Follow/ReleaseCorpse = "Release spirit"
L.Follow/ReleaseCorpse_Info = "Set a key binding to direct dead group members to release their spirit."
L.Follow/SlashCorpse = "/corpse"
L.Follow/SlashFollowMe = "/followme"
L.Follow/TargetedFollowMe = "Targetable /followme"
L.Follow/TargetedFollowMe_Info = "If your current target is a trusted group member, your /followme command will be sent only to that target."
L.Follow/UseSoulstone = "Use Soulstone"
L.Group/CantInviteNotLeader = "I cannot invite you, because I am not the group leader."
L.Group/CantInviteNotTrusted = "I cannot invite you, because you are not on my trusted list."
L.Group/CantPromoteNotLeader = "I cannot promote you, because I am not the group leader."
L.Group/CantPromoteNotTrusted = "I cannot promote you, because you are not on my trusted list."
L.Group/CmdNoPromote = "[Nn][Oo][Pp][Rr][Oo][Mm][Oo][Tt][Ee]"
L.Group/Group = "Group"
L.Group/GroupHelpText = [=[Type "|cffffffff/inviteme|r" to request a group invitation from your current target.

Type "|cffffffff/inviteme Name|r" to request a group invitation from "Name".

Type "|cffffffff/promoteme|r" while in a group to request to be promoted to group leader.]=]
L.Group/Group_Info = "Responds to group invite and promote requests from trusted players."
L.Group/SlashInviteMe = "/inviteme"
L.Group/SlashPromoteMe = "/promoteme"
L.Loot/Loot = "Loot"
L.Loot/Loot_Info = "Automatically switch to Free For All in trusted groups."
L.Mount/Dismount = "Dismount with group"
L.Mount/Dismount_Info = "Dismount when another trusted group member dismounts."
L.Mount/Mount = "Mount"
L.Mount/MountHelpText = " "
L.Mount/Mount_Info = "Group mounting and dismounting."
L.Mount/MountMissing = "%s has no available mount!"
L.Mount/MountRandom = "Use random mount"
L.Mount/MountRandom_Info = [=[Use a random mount of the same type as your trusted group member.
If this is disabled, you will use the same mount if you have it, or the first equivalent mount otherwise.]=]
L.Mount/MountTogether = "Mount with group"
L.Mount/MountTogether_Info = "Mount when another trusted group member mounts."
L.Quest/AbandonQuests = "Abandon quests"
L.Quest/AbandonQuests_Info = "Automatically abandon quests abandoned by trusted group members."
L.Quest/AcceptQuests = "Accept quests"
L.Quest/AcceptQuests_Info = "Automatically accept all quests."
L.Quest/OnlySharedQuests = "Only shared quests"
L.Quest/OnlySharedQuests_Info = "Only accept quests shared by group members, escort quests started by group members, and quests from NPCs that trusted group members have already accepted."
L.Quest/Quest = "Quest"
L.Quest/QuestAbandoned = "%1$s abandoned %2$s."
L.Quest/QuestAccepted = "%1$s accepted %2$s."
L.Quest/QuestHelpText = "If you want an on-screen list of your other characters' quests, I recommend the addon Quecho, by Tekkub."
L.Quest/Quest_Info = "Helps keep group members' quests in sync."
L.Quest/QuestNotShareable = "That quest cannot be shared."
L.Quest/QuestTurnedIn = "%1$s turned in %2$s."
L.Quest/ShareQuests = "Share quests"
L.Quest/ShareQuests_Info = "Automatically share quests you pick up from NPCs."
L.Quest/TurnInQuests = "Turn in quests"
L.Quest/TurnInQuests_Info = "Automatically turn in completed quests to NPCs."
L.Taxi/SlashClearTaxi = "/cleartaxi"
L.Taxi/Taxi = "Taxi"
L.Taxi/TaxiCleared = "Group taxi destination cleared."
L.Taxi/TaxiHelpText = [=[Hold the Shift key while speaking to a flight master to temporarily disable auto-selection.

Type "|cffffffff/cleartaxi|r" to clear the group taxi selection before the normal timeout.]=]
L.Taxi/Taxi_Info = "Selects the same taxi destination as other group members."
L.Taxi/TaxiMismatchError = "%s: Taxi node mismatch."
L.Taxi/TaxiSet = "%1$s set the group taxi to %2$s."
L.Taxi/TaxiTimeoutError = "%s: Taxi timeout reached."
L.Taxi/TaxiTimeout_Info = "Clear the taxi selection after this many seconds."

local CURRENT_LOCALE = GetLocale()
if CURRENT_LOCALE == "enUS" then return end

------------------------------------------------------------------------
-- German
------------------------------------------------------------------------

if CURRENT_LOCALE == "deDE" then

L.Hydra_Notes = "Helfer für Multiboxing und Leveln als Gruppe."
L.Assist/Assist = "Unterstützen"
L.Assist/AssistFailed = "Wegen eines unbekannten Fehler kann %s Euch jetzt nicht unterstützen."
L.Assist/AssistFailedCombat = "%s wird Euch nach dem Kampf unterstützen."
L.Assist/AssistFailedTrust = "%s kann Euch nicht unterstützen, weil Ihr nicht auf ihrer Vertrauensliste seid."
L.Assist/AssistGetMacro = "Makro erhalten"
L.Assist/AssistMacro = "Unterstützen"
L.Assist/AssistMacro_Info = "Belegt eine Taste, um ihre Unterstützungsziel zu helfen."
L.Assist/AssistRespond = "Unterstützen"
L.Assist/AssistRespond_Info = "Auf Unterstützungsanfragen von vertrauenswürdige Gruppenmitglieder reagieren."
L.Assist/AssistSet = "%s wird Euch jetzt unterstützen."
L.Assist/AssistUnset = "%s wird %s anstatt Euer jetzt unterstützen."
L.Assist/NobodyAssisting = "Niemand unterstützt Euch momentan."
L.Assist/RequestAssist = "Assistenz anfordern"
L.Assist/RequestAssist_Info = "Belegt eine Taste, um alle Gruppenmitglieder befehlen, Euch als ihr Unterstützungsziel zu einstellen."
L.Assist/SlashAssistMe = "/assistieremir"
L.Automation/AcceptCombatRes = "Wiederbelebungen im Kampf annehmen"
L.Automation/AcceptCombatRes_Info = "Nehmt Wiederbelebungen im Kampf von allen Gruppenmitglieder an."
L.Automation/AcceptedRes = "Eine Wiederbelebung von %s wurde angenommen."
L.Automation/AcceptedSummon = "Eine Beschwörung von %1$s nach %2$s wurde angenommen."
L.Automation/AcceptedSummonCombat = "Eine Beschwörung wird nach dem Kampf angenommen..."
L.Automation/AcceptRes = "Wiederbelebungen annehmen"
L.Automation/AcceptRes_Info = "Nehmt Wiederbelebungen außerhalb des Kampfes von allen Gruppenmitglieder an."
L.Automation/AcceptSummons = "Beschwörungen annehmen"
L.Automation/AcceptSummons_Info = "Nehmt Beschwörungen von vertrauenswürdige Spieler an."
L.Automation/Automation = "Automatisierung"
L.Automation/Automation_Info = "Automatisiert einige einfache wiederholende Aktionen, wie das Klicken auf häufige Dialoge."
L.Automation/DeclineArenas = "Arenateams blockieren"
L.Automation/DeclineArenas_Info = "Blockiert Arenateameinladungen ab."
L.Automation/DeclinedArena = "Arenateameinladung von %s wurde blockiert."
L.Automation/DeclinedArenaPetition = "Arenateamsatzung von %s wurde blockiert."
L.Automation/DeclinedDuel = "Duellanfrage von %s wurde blockiert."
L.Automation/DeclinedGuild = "Gildenanfrage von %s wurde blockiert."
L.Automation/DeclinedGuildPetition = "Gildensatzung von %s wurde blockiert."
L.Automation/DeclineDuels = "Duelle blockieren"
L.Automation/DeclineDuels_Info = "Duellanfragen von allen Spielder blockieren."
L.Automation/DeclineGuilds = "Gilde blockieren"
L.Automation/DeclineGuilds_Info = "Gildenanfragen und -satzung von allen Spieler blockieren."
L.Automation/NoRepairMoney = "Nicht genug Geld für Reparaturen zu bezahlen!"
L.Automation/NoRepairMoneyGuild = "Nicht genug Gildenbankgeld für Reparaturen zu bezahlen!"
L.Automation/Repair = "Gegenstände reparieren"
L.Automation/Repaired = "Alle Gegenstände wurden für %s repariert."
L.Automation/RepairedGuild = "Alle Gegenstände wurden für %s aus der Gildenbank repariert."
L.Automation/RepairGuild = "Gildenbankgeld ausgeben"
L.Automation/RepairGuild_Info = "Bezahlt für Reparaturen aus der Gildenbank, wenn möglich."
L.Automation/Repair_Info = "Repariert alle Gegenstände auf die Interaktion mit einem Händler."
L.Automation/SellJunk = "Müll verkaufen"
L.Automation/SellJunk_Info = "Verkauft alle grau Artikel auf die Interaktion mit einem Händler."
L.Automation/SoldJunk = "%1$d |4Stück Müll wurde:Stücke Müll wurden; für %2$s verkauft."
L.Automation/SummonExpired = "Beschwörung abgelaufen!"
L.Chat/AppFocus = "Spiel im Fokus"
L.Chat/Chat = "Chat"
L.Chat/ChatHelpText = [=[Gebt eine Nachricht in Gruppenchat ein, um zum letzten Flüstern von jedem Gruppenmitglieder weitergeleitet zu antworten.

Gebt "|cffffffff@Name Nachricht hier|r" in Gruppenchat ein, um zum letzten Flüstern von "Name" weitergeleitet zu antworten.

Flüstert "|cffffffff@Name Nachricht hier|r" einen Charakter, um der zu befehlen, die Nachricht an "Name" zu flüstern.]=]
L.Chat/Chat_Info = "Flüstern, die durch inaktive Charaktere eingehen, werden an Gruppenchat weitergeleitet, und Antworten werden an den eigentlichen Absender weitergeleitet."
L.Chat/DetectionMethod = "Wahrnehmungsmethode"
L.Chat/DetectionMethod_Info = [=[Wählt die Methode zur Erfassung der Hauptcharakter aus.

Wenn Ihr mehrere Computer verwendet, oder mehrere Instanzen des Spiels führt aus, der "Spiel im Fokus" Methode wird wahrscheinlich für Euch nicht funktionen, und Ihr müsst sicherstellen, dass Eure Hauptcharakter der Gruppenleiter ist.]=]
L.Chat/GroupLeader = "Gruppenleiter"
L.Chat/GroupTimeoutError = "Gruppenweiterleitungsablauf überschritten."
L.Chat/GroupTimeout_Info = "Wenn diese viele Sekunden sind vergangen, seit die letzte Nachricht weitergeleitet wurde, neue Nachrichten in Gruppenchat werden nicht weitergeleitet, außer wenn die Ziel explizit angegeben wird."
L.Chat/WhisperFrom = "%1$s hat ein Flüstern von %2$s erhalten."
L.Chat/WhisperFromBnet = [=[%1$s hat ein Battle.net-Flustern von %2$s erhalten:
%3$s]=]
L.Chat/WhisperFromConvo = [=[%1$s hat eine Battle.net-Nachricht von %2$s erhalten:
%3$s]=]
L.Chat/WhisperFromGM = "%s hat eine Nachrict von einem GM erhalten!"
L.Chat/WhisperTimeoutError = "Flüsternablauf überschritten."
L.Core/AddedTrusted = "%s wurde auf der Vertrauensliste hinzugefügt."
L.Core/AddGroup = "Gruppe hinzufügen"
L.Core/AddGroup_Info = "Fügt alle Spieler aus die Gruppe auf der Vertrauensliste hinzu."
L.Core/AddName = "Name hinzufügen"
L.Core/AddName_Info = "Fügt einen Name auf der Vertrauensliste hinzu."
L.Core/ClickForOptions = "Klick für optionen."
L.Core/CoreHelpText = [=[Hydra funktioniert auf einer Vertrauensbasis. Legt fest, welche Spieler zu vertrauen, und Hydra aktiviert oder deaktiviert Funktionen auf der Grundlage, ob alle Spieler in der Gruppe auf der Vertrauensliste sind.

Zum Beispiel, Flüstern werden zu die Gruppe nur weitergeleitet, wenn jeder in der Gruppe ist auf der Vertrauensliste.]=]
L.Core/Enable_Info = "Aktiviert dieses Modul."
L.Core/Hydra_Info = "Hydra ist ein Helfer für Multiboxing und Stufenaufstiegen als Gruppe, der versucht, die Notwendigkeit zu minimieren, um die Sekundärcharakteren kontrollieren."
L.Core/RemoveAll = "Alle entfernen"
L.Core/RemoveAll_Info = "Entfernt alle Namen aus der Vertrauensliste."
L.Core/RemovedTrusted = "%s wurde aus der Vertrauensliste entfernt."
L.Core/RemoveName = "Name enterfernen"
L.Core/RemoveName_Info = "Enterfernt einen Name aus der Vertrauensliste."
L.Core/Timeout = "Ablauf"
L.Core/Verbose = "Wortreich"
L.Core/Verbose_Info = "Aktiviert Benachrichtigungen von diesem Modul."
L.Debug/Debug = "Debugging"
L.Debug/DebugCore = "Kern"
L.Debug/Debug_Info = "Debugging-Meldungen für die ausgewählten Teile von Hydra aktivieren."
L.Follow/AcceptCorpse = "Zu Leichnam wiederbeleben"
L.Follow/AcceptCorpse_Info = "Belegt eine Taste, um tote Gruppenmitglieder befehlen, in ihre Leichnam wiederzubeleben."
L.Follow/CanReincarnate = "%s kann wiederbeleben."
L.Follow/CanSelfRes = "%s kann selbst wiederbeleben."
L.Follow/CantRes = "%s kann nicht wiederbeleben!"
L.Follow/CantResDelay = "%1$s kann nicht für %2$d Sekuden mehr wiederbeleben."
L.Follow/CanUseSoulstone = "%s kann einen Seelenstein verwenden."
L.Follow/CmdAccept = "a[kn]?[zn]?e?[ph]?[tm]?i?e?r?e?n?"
L.Follow/CmdRelease = "f?r?e?i?l?a?s?s?e?n?"
L.Follow/Follow = "Folgen"
L.Follow/FollowHelpText = [=[Gebt "|cffffffff/folgenmich|r" ein, um nahe Gruppenmitglieder zu befehlen, Euch zu folgen.

Gebt "|cffffffff/leichnam freilassen|r" ein, um tote Gruppenmitglieder befehlen, ihre Geister zu freilassen.

Gebt "|cffffffff/leichnam annehmen|r" ein, um tote Gruppenmitglieder befehlen, in ihre Leichnam wiederzubeleben.]=]
L.Follow/Follow_Info = "Dieses Modul gehorcht auf die Folgeantragen von vertrauenswürdige Gruppenmitglieder."
L.Follow/FollowingYouStart = "%s folgt Euch jetzt."
L.Follow/FollowingYouStop = "%s folgt Euch nicht mehr."
L.Follow/FollowMe = "Folgende anfordern"
L.Follow/FollowMe_Info = "Belegt eine Taste, um nahe Gruppenmitglieder befehlen, Euch zu folgen."
L.Follow/FollowTarget = "Ziel folgen"
L.Follow/FollowTarget_Info = "Belegt eine Taste, um Eure aktuelle Ziel folgen."
L.Follow/FollowTooFar = "%s ist zu weit weg, um zu folgen!"
L.Follow/RefollowAfterCombat = "Nach dem Kampf wiederfolgen"
L.Follow/RefollowAfterCombat_Info = "Versucht automatisch Eure letzte folgende Ziel nach dem Kampf wieder zu folgen."
L.Follow/ReleaseCorpse = "Geister freilassen"
L.Follow/ReleaseCorpse_Info = "Belegt eine Taste, um tote Gruppenmitglieder befehlen, ihre Geister zu freilassen."
L.Follow/SlashCorpse = "/leichnam"
L.Follow/SlashFollowMe = "/folgenmich"
L.Follow/TargetedFollowMe = "Anzielbare /folgenmich"
L.Follow/TargetedFollowMe_Info = "Wenn Eure aktuelle Ziel ist ein vertrauenswürdiges Gruppenmitglied, Eure \"/folgenmich\"-Befehl wird nur auf diese Ziel gesendet."
L.Group/CantInviteNotLeader = "Ich kann Euch nicht einladen, weil ich der Gruppenanführer nicht bin."
L.Group/CantInviteNotTrusted = "Ich kann Euch nicht einladen, weil Ihr auf meiner Vertrauensliste nicht seid."
L.Group/CantPromoteNotLeader = "Ich kann Euch nicht befördern, weil ich der Gruppenanführer nicht bin."
L.Group/CantPromoteNotTrusted = "Ich kann Euch nicht befördern, weil Ihr auf meiner Vertrauensliste nicht seid."
L.Group/CmdNoPromote = "[Nn][Ii][Cc][Hh][Tt][Bb][Ee][Ff][Öö][Rr][Dd][Ee][Rr][Nn]"
L.Group/Group = "Gruppe"
L.Group/GroupHelpText = [=[Gebt "|cffffffff/ladetmich|r" ein, um eine Gruppeneinladung von Eure aktuellen Ziel zu anfordern.

Gebt "|cffffffff/ladetmich Name|r" ein, um eine Gruppeneinladung von "Name" zu anfordern.

Gebt "|cffffffff/befördernmich|r" ein, während Ihr in einer Gruppe seid, um eine Förderung als Gruppenanführer zu anforden.]=]
L.Group/Group_Info = "Dieses Modul gehorcht auf Gruppeneinladungen und Förderungsantragen von vertrauenswürdige Spieler."
L.Group/SlashInviteMe = "/einladenmich"
L.Group/SlashPromoteMe = "/befördernmich"
L.Loot/Loot = "Plündern"
L.Loot/Loot_Info = "Plündern auf \"Jeder gegen Jeden\" in vertrauenswürdigen Gruppen automatisch umschalten."
L.Mount/Dismount = "Absitzen bei Gruppe"
L.Mount/Dismount_Info = "Sitzt ab, wenn ein anderes vertrauenswürdiges Gruppenmitglied sitzt ab."
L.Mount/Mount = "Aufsitzen"
L.Mount/Mount_Info = "Mit diesem Modul kann die Gruppe zusammen aufsizten und absitzen."
L.Mount/MountMissing = "%s hat keine verfügbaren Reittiere!"
L.Mount/MountRandom = "Zufälliges Reittier verwenden"
L.Mount/MountRandom_Info = [=[Verwendet ein zufälliges Reittier der gleichen Art wie Eure vertrauenswürdigen Gruppenmitglied.
Wenn diese Option deaktiviert, werdet Ihr das gleiche Reittier verwenden, wenn Ihr das habt, oder sonst das erste Reittier der gleichen Art.]=]
L.Mount/MountTogether = "Mit Gruppe aufsitzen"
L.Mount/MountTogether_Info = "Sitzt auf, wenn ein anderes vertrauenswürdiges Gruppenmitglied sitzt auf."
L.Quest/AbandonQuests = "Quests abbrechen"
L.Quest/AbandonQuests_Info = "Automatisch brecht die Quests ab, die vertrauenswürdige Gruppenmitglieder abbrechen."
L.Quest/AcceptQuests = "Quests annehmen"
L.Quest/AcceptQuests_Info = "Automatisch nehmt alle Quests ab."
L.Quest/OnlySharedQuests = "Nur gemeinsame Quests"
L.Quest/OnlySharedQuests_Info = "Nur Quests annehmen, die von Gruppenmitgliedern geteilt werden, die Escort-Quests von Gruppenmitgliedern gestartet sind, die eine vertrauenswürdige Gruppenmitglied bereits von einem NSC nahm an."
L.Quest/Quest = "Quests"
L.Quest/QuestAbandoned = "%1$s hat die Quest '%2$s' abgebrochen."
L.Quest/QuestAccepted = "%1$s had die Quest '%2$s' angenommen."
L.Quest/QuestHelpText = "Wenn Ihr eine Liste der Quests Euer weiteren Charaktere wollt, ich empfehle, dass Ihr das Addon 'Quecho' von Tekkub verwendet."
L.Quest/Quest_Info = "Mit diesem Modul kann die Gruppe Quests zusammen machen."
L.Quest/QuestNotShareable = "Diese Quest kann nicht geteilt werden."
L.Quest/QuestTurnedIn = "%1$s hat die Quest '%2$s'  abgeschlossen."
L.Quest/ShareQuests = "Quests teilen"
L.Quest/ShareQuests_Info = "Automatisch teilt die Quests, die Ihr von NSCs nehmt an."
L.Quest/TurnInQuests = "Quests abschließen"
L.Quest/TurnInQuests_Info = "Automatisch schließt die Quests zu NSCs ab."
L.Taxi/SlashClearTaxi = "/fluglöschen"
L.Taxi/Taxi = "Fliegen"
L.Taxi/TaxiCleared = "Gruppenflugziel erlöscht."
L.Taxi/TaxiHelpText = [=[Drückt die SHIFT-Taste auf die Interaktion mit einem Flugmeister, um die automatische Auswahl vorübergehend deaktivieren.

Gebt "|cffffffff/fluglöschen|r" ein, um die Gruppenflugziel vor der üblichen Ablaufzeit zu löschen.]=]
L.Taxi/Taxi_Info = "Mit diesem Modul kann die Gruppe zusammen fliegen."
L.Taxi/TaxiMismatchError = "%s: Flugziele stimmen nicht überein!"
L.Taxi/TaxiSet = "%1$s hat die Gruppenflugziel auf %2$s festgelegt."
L.Taxi/TaxiTimeoutError = "%s: Ablaufzeit des Gruppenflugziels ist vorbei."
L.Taxi/TaxiTimeout_Info = "Wenn diese viele Sekunden sind vergangen, die Gruppenflugziel wird gelöscht."

return end

------------------------------------------------------------------------
-- Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esES" then

L.Hydra_Notes = "Ayudante para el multibox y la subir en grupo."
L.Automation/AcceptCombatRes = "Aceptar resurecciones en combate"
L.Automation/AcceptCombatRes_Info = "Aceptar resurecciones en combate por los miembres del grupo."
L.Automation/AcceptedRes = "Aceptó una resurrección de %s."
L.Automation/AcceptedSummon = "Aceptó invocar de %1$s a %2$s."
L.Automation/AcceptedSummonCombat = "Aceptará invocar cuando se termina el combate ..."
L.Automation/AcceptRes = "Aceptar resurecciones"
L.Automation/AcceptRes_Info = "Aceptar los resurecciones ofrecidos fuera de combate por los miembres del grupo."
L.Automation/AcceptSummons = "Aceptar invocaciones"
L.Automation/AcceptSummons_Info = "Aceptar los invocaciones ofrecidos por los jugadores de confianza."
L.Automation/Automation = "Automatización"
L.Automation/Automation_Info = "Automatiza algunas tareas sencillas, como hacer clic en los cuadros de diálogo comunes."
L.Automation/DeclineArenas = "Rechazar equipos de arena"
L.Automation/DeclineArenas_Info = "Rechazar invitaciones y peticiones de equipos de arena de todo jugadores."
L.Automation/DeclinedArena = "Rechazó una invitación a equipo de arena de %s."
L.Automation/DeclinedArenaPetition = "Rechazó una petición de equipo de arena de %s."
L.Automation/DeclinedDuel = "Rechazó una invitación a duelo de %s."
L.Automation/DeclinedGuild = "Rechazó una invitación a hermandad de %s."
L.Automation/DeclinedGuildPetition = "Rechazó una petición de hermandad de %s."
L.Automation/DeclineDuels = "Rechazar duelos"
L.Automation/DeclineDuels_Info = "Rechazar invitaciones a duelos de todos jugadores."
L.Automation/DeclineGuilds = "Rechazar hermandades"
L.Automation/DeclineGuilds_Info = "Rechazar invitaciones y peticiones a hermandades de todos jugadores."
L.Automation/NoRepairMoney = "¡No tienes suficiente dinero para reparar!"
L.Automation/NoRepairMoneyGuild = "¡La hermandad no tiene suficiente dinero para reparar!"
L.Automation/Repair = "Reparar equipos"
L.Automation/Repaired = "Reparó todos los equpios por %s."
L.Automation/RepairedGuild = "Reparó todos los equipos por %s del dinero de la hermandad."
L.Automation/RepairGuild = "Pagar la reparación con el dinero de la hermandad cuando sea posible."
L.Automation/RepairGuild_Info = "Pagar la reparación con el dinero de la hermandad cuando sea posible."
L.Automation/Repair_Info = "Reparar todos equipos cuando hablas con un mercador de reparación."
L.Automation/SellJunk = "Vender chatarra"
L.Automation/SellJunk_Info = "Vender todas las chatarra (objetos gris) en el inventario cuando hablas con un vendedor."
L.Automation/SoldJunk = "Vendió %1$d |4artículo:artículos; de chatarra por %2$s."
L.Automation/SummonExpired = "La invocación expiró!"
L.Chat/AppFocus = "Programa en foco"
L.Chat/Chat = "Chat"
L.Chat/ChatHelpText = [=[Escribe en el chat de grupo para responder a la última susurro que se reenvió al chat de grupo por un otro personaje.

Escribe "|cffffffff@Nombre Mensaje aquí|r" para responder a la última susurro que se reenvió por el personaje "Nombre".

Escribe "|cffffffff@Nombre Mensaje aquí|r" en un susurro al otro personaje para enviar por ese personaje el mensaje como un susurro a "Nombre".]=]
L.Chat/Chat_Info = "Reenvía al chat del grupo los susurros que se enviaron a los personajes inactivos, y reenvía las respuestas al remitente original."
L.Chat/DetectionMethod = "Método de detección"
L.Chat/DetectionMethod_Info = [=[Seleccione el método para utilizar para detectar el personaje principal.

Si estás jugando en varios equipos, o estás ejecutando en la misma computadora múltiples copias de WoW en el modo de ventana, el método de detección "Programa en foco" probablemente no funcione. En este caso, debe utilizar el método "Líder del grupo" y asegúrate de que tu personaje principal es el líder del grupo.]=]
L.Chat/GroupLeader = "Líder del grupo"
L.Chat/GroupTimeoutError = "Se ha alcanzado el tiempo de espera para el chat de grupo."
L.Chat/GroupTimeout_Info = "Después de estos segundos desde el último susurro, los mensajes escritos en el chat de grupo no se reenvían, a menos especificar explícitamente el objetivo."
L.Chat/WhisperFrom = "%1$s recibió un susurro de %2$s."
L.Chat/WhisperFromBnet = [=[%1$s recibió un susurro de Battle.net de %2$s:
%3$s]=]
L.Chat/WhisperFromConvo = [=[%1$s recibió un mensaje en conversación de %2$s:
%3$s]=]
L.Chat/WhisperFromGM = "¡%s recibió un susurro de un MJ!"
L.Chat/WhisperTimeoutError = "Se ha alcanzado el tiempo de espera para los susurros."
L.Core/AddedTrusted = "%s ha sido añadido a la lista de confianza."
L.Core/AddGroup = "Añadir el grupo"
L.Core/AddGroup_Info = "Añadir a la lista de confianza los nombres de todos los personajes en tu grupo actual."
L.Core/AddName = "Añadir un nombre"
L.Core/AddName_Info = "Añadir a la lista de confianza un nombre de personaje."
L.Core/ClickForOptions = "Clic para opciones."
L.Core/CoreHelpText = [=[Hydra functiona sobre la base de "confianza". Añada una lista de personajes de tu confianza, si son tus personajes multibox, o tus amigos, y las funciones se activan o desactivan dependiendo de si estás en una grupo con sólo personajes de confianza.

Por ejemplo, los susurros sólo se reenvían al chat de grupo si todos en el grupo son de confianza.]=]
L.Core/Enable_Info = "Activar este módulo."
L.Core/Hydra_Info = "Hydra está un ayudante para el multibox y la subir en grupo, que trata de minimizar la necesidad para controlar los personajes secundarios."
L.Core/RemoveAll = "Quitar todos"
L.Core/RemoveAll_Info = "Vaciar la lista de confianza por la eliminación de todos los nombres de personajes."
L.Core/RemovedTrusted = "%s ha sido quitado de la lista de confianza."
L.Core/RemoveName = "Quitar un numbre"
L.Core/RemoveName_Info = "Quitar de la lista de confianza un nombre de personaje."
L.Core/Timeout = "Tiempo de espera"
L.Core/Verbose = "Verboso"
L.Core/Verbose_Info = "Activar mensajes de notificación de este módulo."
L.Debug/Debug = "Depurar"
L.Debug/DebugCore = "Núcleo"
L.Debug/Debug_Info = "Activar los mensajes de depuración para los partes seleccionados de Hydra."
L.Follow/AcceptCorpse = "Recuperar cadáver"
L.Follow/AcceptCorpse_Info = "Asignar una tecla para mandar los miembros muertos del grupo a recuperar los cadáveres."
L.Follow/CanReincarnate = "%s puede usar Reencarnación."
L.Follow/CanSelfRes = "%s puede resucitarse."
L.Follow/CantRes = "¡%s no puede ser resucitado!"
L.Follow/CantResDelay = "%1$s no puede ser resucitado por otros %2$d segundos!"
L.Follow/CanUseSoulstone = "%s puede usar una Piedra de alma."
L.Follow/CmdAccept = "[ar]e?[cs]?[eu]?[pc]?[ei]?[rt]?a?r?"
L.Follow/CmdRelease = "libe?r?a?r?"
L.Follow/Follow = "Seguir"
L.Follow/FollowHelpText = [=[Escriba "|cffffffff/seguirme|r" para mandar los miembres cercanos del grupo a seguirte.

Escriba "|cffffffff/cadaver libera|r" para mandar los miembros muertos del grupo a liberar los espíritus.

Escriba "|cffffffff/cadaver recupera|r" para mandar mandar los miembros muertos del grupo a recuperar los cadáveres.]=]
L.Follow/Follow_Info = "Responde a los comandos de seguiente por los miembros de confianza del grupo."
L.Follow/FollowingYouStart = "%s te está siguiendo."
L.Follow/FollowingYouStop = "%s dejó de seguirte."
L.Follow/FollowMe = "¡Sígueme!"
L.Follow/FollowMe_Info = "Asignar una tecla para mandar los miembres cercanos del grupo a seguirte."
L.Follow/FollowTarget = "Seguir objetivo"
L.Follow/FollowTarget_Info = "Asignar una tecla para seguir el objetivo actual."
L.Follow/FollowTooFar = "%s está demasiado lejos para seguir!"
L.Follow/RefollowAfterCombat = "Resuigir después de combate"
L.Follow/RefollowAfterCombat_Info = "Automáticamente tratará seguir el objetivo seguido previamente cuando termina el combate."
L.Follow/Reincarnate = "Reencarnarse"
L.Follow/ReleaseCorpse = "Liberar el espíritu"
L.Follow/ReleaseCorpse_Info = "Asignar una tecla para mandar los miembros muertos del grupo a liberar los espíritus."
L.Follow/SlashCorpse = "/cadaver"
L.Follow/SlashFollowMe = "/sigueme"
L.Follow/TargetedFollowMe = "Enviar /sigueme al objetivo"
L.Follow/TargetedFollowMe_Info = "Si el objetivo actual es un miembro de confianza del grupo, el comando se enviará sólo a ese personaje, en lugar del grupo entero."
L.Follow/UseSoulstone = "Usa Piedra de alma"
L.Group/CantInviteNotLeader = "No te puedo invitar, porque no estoy el líder del grupo."
L.Group/CantInviteNotTrusted = "No te puedo invitar, porque no estás en mi lista de confianza."
L.Group/CantPromoteNotLeader = "No te puedo promover, porque no estoy el líder del grupo."
L.Group/CantPromoteNotTrusted = "No te puedo promover, porque no estás en mi lista de confianza."
L.Group/CmdNoPromote = "[Nn][Oo][Pp][Rr][Oo][Mm][Oo][Vv][Ee][Rr]?"
L.Group/Group = "Grupo"
L.Group/GroupHelpText = [=[Escribe "|cffffffff/invitarme|r" para solictar una invitación de grupo de tu objetivo.

Escribe "|cffffffff/invitarme Nombre|r" para solictar una invitación de grupo del personaje "Nombre".

Escribe "|cffffffff/promoverme|r" mientras estás en el grupo para solicitar una promoción al líder del grupo.]=]
L.Group/Group_Info = "Responde a los comandos de invitar o promover de los jugadores de confianza."
L.Group/SlashInviteMe = "/invitarme"
L.Group/SlashPromoteMe = "/promoverme"
L.Loot/Loot = "Botín"
L.Loot/Loot_Info = "Cambiar automáticamente el método de despojo al modo libre en grupos confianzos."
L.Mount/Dismount = "Desmontar juntos"
L.Mount/Dismount_Info = "Desmontar cuando desmonta un miembro de confianza del grupo."
L.Mount/Mount = "Montura"
L.Mount/Mount_Info = "Montar y desmontar como un grupo."
L.Mount/MountMissing = "¡%s no tiene una montura equivalente!"
L.Mount/MountRandom = "Monturas aleatorias"
L.Mount/MountRandom_Info = [=[Al montar automáticamente, utilizar una montura aleatoria del mismo tipo del miembro de confianza del grupo.
Si está desactivada, vas a utilizar la misma monutra si lo tienen, o el equivalente primero a encontrar.]=]
L.Mount/MountTogether = "Montar juntos"
L.Mount/MountTogether_Info = "Montar cuando desmonta un miembro de confianza del grupo."
L.Quest/AbandonQuests = "Abandonar las misiones"
L.Quest/AbandonQuests_Info = "Abandonar las misiones que se abandonaron por otros miembros de confianza del grupo."
L.Quest/AcceptQuests = "Aceptar las misiones"
L.Quest/AcceptQuests_Info = "Aceptar todos las misiones."
L.Quest/OnlySharedQuests = "Sólo las misiones compartidos"
L.Quest/OnlySharedQuests_Info = "Aceptar sólo las misiones que se compartieron por otros miembros del grupo, las misiones de escoltar que se iniciaron por otros miembros del grupo, y las misiones de PNJs que ya han compartido por los miembres de confianza del grupo."
L.Quest/Quest = "Misión"
L.Quest/QuestAbandoned = "%1$s abandonó %2$s."
L.Quest/QuestAccepted = "%1$s aceptó %2$s."
L.Quest/QuestHelpText = "Si desea una lista en la pantalla de los estados de las misiones de los miembros del grupo, te recomiendo el addon Quecho, por Tekkub."
L.Quest/Quest_Info = "Ayuda a mantener en sincronía las misiones de las miembros del grupo."
L.Quest/QuestNotShareable = "Esta misión no se puede compartir."
L.Quest/QuestTurnedIn = "%1$s entregó %2$s."
L.Quest/ShareQuests = "Compartir las misiones"
L.Quest/ShareQuests_Info = "Compartir las misiones que lo aceptaron de PNJs."
L.Quest/TurnInQuests = "Entregar las misiones"
L.Quest/TurnInQuests_Info = "Entregar a PNJs las misiones completadas."
L.Taxi/SlashClearTaxi = "/borrartaxi"
L.Taxi/Taxi = "Taxi"
L.Taxi/TaxiCleared = "El destino compartido de taxi ha sido borrada."
L.Taxi/TaxiHelpText = [=[Pulse la tecla Mayús cuando hablas con un maestro de vuelo para ignorar el destino seleccionado compartido.

Escribe "|cffffffff/borrartaxi|r" para borrar el destino compardito antes de que el tiempo de espera se alcance.]=]
L.Taxi/Taxi_Info = "Seleccionar el mismo destino de taxi que los otros miembros del grupo."
L.Taxi/TaxiMismatchError = "%s: El destino no coincide."
L.Taxi/TaxiSet = "%1$s estableció el destino compartido a %2$s."
L.Taxi/TaxiTimeoutError = "%s: Se ha alcanzado el tiempo de espera para el taxi."
L.Taxi/TaxiTimeout_Info = "Borrar la selección del destino compartido después de estos segundos."

return end

------------------------------------------------------------------------
-- Latin American Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esMX" then

L.Hydra_Notes = "Ayudante para el multibox y la subir en grupo."
L.Automation/AcceptCombatRes = "Aceptar resurecciones en combate"
L.Automation/AcceptCombatRes_Info = "Aceptar resurecciones en combate por los miembres del grupo."
L.Automation/AcceptedRes = "Aceptó una resurrección de %s."
L.Automation/AcceptedSummon = "Aceptó invocar de %1$s a %2$s."
L.Automation/AcceptedSummonCombat = "Aceptará invocar cuando se termina el combate ..."
L.Automation/AcceptRes = "Aceptar resurecciones"
L.Automation/AcceptRes_Info = "Aceptar los resurecciones ofrecidos fuera de combate por los miembres del grupo."
L.Automation/AcceptSummons = "Aceptar invocaciones"
L.Automation/AcceptSummons_Info = "Aceptar los invocaciones ofrecidos por los jugadores de confianza."
L.Automation/Automation = "Automatización"
L.Automation/Automation_Info = "Automatiza algunas tareas sencillas, como hacer clic en los cuadros de diálogo comunes."
L.Automation/DeclineArenas = "Rechazar equipos de arena"
L.Automation/DeclineArenas_Info = "Rechazar invitaciones y peticiones de equipos de arena de todo jugadores."
L.Automation/DeclinedArena = "Rechazó una invitación a equipo de arena de %s."
L.Automation/DeclinedArenaPetition = "Rechazó una petición de equipo de arena de %s."
L.Automation/DeclinedDuel = "Rechazó una invitación a duelo de %s."
L.Automation/DeclinedGuild = "Rechazó una invitación a hermandad de %s."
L.Automation/DeclinedGuildPetition = "Rechazó una petición de hermandad de %s."
L.Automation/DeclineDuels = "Rechazar duelos"
L.Automation/DeclineDuels_Info = "Rechazar invitaciones a duelos de todos jugadores."
L.Automation/DeclineGuilds = "Rechazar hermandades"
L.Automation/DeclineGuilds_Info = "Rechazar invitaciones y peticiones a hermandades de todos jugadores."
L.Automation/NoRepairMoney = "¡No tienes suficiente dinero para reparar!"
L.Automation/NoRepairMoneyGuild = "¡La hermandad no tiene suficiente dinero para reparar!"
L.Automation/Repair = "Reparar equipos"
L.Automation/Repaired = "Reparó todos los equpios por %s."
L.Automation/RepairedGuild = "Reparó todos los equipos por %s del dinero de la hermandad."
L.Automation/RepairGuild = "Pagar la reparación con el dinero de la hermandad cuando sea posible."
L.Automation/RepairGuild_Info = "Pagar la reparación con el dinero de la hermandad cuando sea posible."
L.Automation/Repair_Info = "Reparar todos equipos cuando hablas con un mercador de reparación."
L.Automation/SellJunk = "Vender chatarra"
L.Automation/SellJunk_Info = "Vender todas las chatarra (objetos gris) en el inventario cuando hablas con un vendedor."
L.Automation/SoldJunk = "Vendió %1$d |4artículo:artículos; de chatarra por %2$s."
L.Automation/SummonExpired = "La invocación expiró!"
L.Chat/AppFocus = "Programa en foco"
L.Chat/Chat = "Chat"
L.Chat/ChatHelpText = [=[Escribe en el chat de grupo para responder a la última susurro que se reenvió al chat de grupo por un otro personaje.

Escribe "|cffffffff@Nombre Mensaje aquí|r" para responder a la última susurro que se reenvió por el personaje "Nombre".

Escribe "|cffffffff@Nombre Mensaje aquí|r" en un susurro al otro personaje para enviar por ese personaje el mensaje como un susurro a "Nombre".]=]
L.Chat/Chat_Info = "Reenvía al chat del grupo los susurros que se enviaron a los personajes inactivos, y reenvía las respuestas al remitente original."
L.Chat/DetectionMethod = "Método de detección"
L.Chat/DetectionMethod_Info = [=[Seleccione el método para utilizar para detectar el personaje principal.

Si estás jugando en varios equipos, o estás ejecutando en la misma computadora múltiples copias de WoW en el modo de ventana, el método de detección "Programa en foco" probablemente no funcione. En este caso, debe utilizar el método "Líder del grupo" y asegúrate de que tu personaje principal es el líder del grupo.]=]
L.Chat/GroupLeader = "Líder del grupo"
L.Chat/GroupTimeoutError = "Se ha alcanzado el tiempo de espera para el chat de grupo."
L.Chat/GroupTimeout_Info = "Después de estos segundos desde el último susurro, los mensajes escritos en el chat de grupo no se reenvían, a menos especificar explícitamente el objetivo."
L.Chat/WhisperFrom = "%1$s recibió un susurro de %2$s."
L.Chat/WhisperFromBnet = [=[%1$s recibió un susurro de Battle.net de %2$s:
%3$s]=]
L.Chat/WhisperFromConvo = [=[%1$s recibió un mensaje en conversación de %2$s:
%3$s]=]
L.Chat/WhisperFromGM = "¡%s recibió un susurro de un MJ!"
L.Chat/WhisperTimeoutError = "Se ha alcanzado el tiempo de espera para los susurros."
L.Core/AddedTrusted = "%s ha sido añadido a la lista de confianza."
L.Core/AddGroup = "Añadir el grupo"
L.Core/AddGroup_Info = "Añadir a la lista de confianza los nombres de todos los personajes en tu grupo actual."
L.Core/AddName = "Añadir un nombre"
L.Core/AddName_Info = "Añadir a la lista de confianza un nombre de personaje."
L.Core/ClickForOptions = "Clic para opciones."
L.Core/CoreHelpText = [=[Hydra functiona sobre la base de "confianza". Añada una lista de personajes de tu confianza, si son tus personajes multibox, o tus amigos, y las funciones se activan o desactivan dependiendo de si estás en una grupo con sólo personajes de confianza.

Por ejemplo, los susurros sólo se reenvían al chat de grupo si todos en el grupo son de confianza.]=]
L.Core/Enable_Info = "Activar este módulo."
L.Core/Hydra_Info = "Hydra está un ayudante para el multibox y la subir en grupo, que trata de minimizar la necesidad para controlar los personajes secundarios."
L.Core/RemoveAll = "Quitar todos"
L.Core/RemoveAll_Info = "Vaciar la lista de confianza por la eliminación de todos los nombres de personajes."
L.Core/RemovedTrusted = "%s ha sido quitado de la lista de confianza."
L.Core/RemoveName = "Quitar un numbre"
L.Core/RemoveName_Info = "Quitar de la lista de confianza un nombre de personaje."
L.Core/Timeout = "Tiempo de espera"
L.Core/Verbose = "Verboso"
L.Core/Verbose_Info = "Activar mensajes de notificación de este módulo."
L.Debug/Debug = "Depurar"
L.Debug/DebugCore = "Núcleo"
L.Debug/Debug_Info = "Activar los mensajes de depuración para los partes seleccionados de Hydra."
L.Follow/AcceptCorpse = "Recuperar cadáver"
L.Follow/AcceptCorpse_Info = "Asignar una tecla para mandar los miembros muertos del grupo a recuperar los cadáveres."
L.Follow/CanReincarnate = "%s puede usar Reencarnación."
L.Follow/CanSelfRes = "%s puede resucitarse."
L.Follow/CantRes = "¡%s no puede ser resucitado!"
L.Follow/CantResDelay = "%1$s no puede ser resucitado por otros %2$d segundos!"
L.Follow/CanUseSoulstone = "%s puede usar una Piedra de alma."
L.Follow/CmdAccept = "[ar]e?[cs]?[eu]?[pc]?[ei]?[rt]?a?r?"
L.Follow/CmdRelease = "libe?r?a?r?"
L.Follow/Follow = "Seguir"
L.Follow/FollowHelpText = [=[Escriba "|cffffffff/seguirme|r" para mandar los miembres cercanos del grupo a seguirte.

Escriba "|cffffffff/cadaver libera|r" para mandar los miembros muertos del grupo a liberar los espíritus.

Escriba "|cffffffff/cadaver recupera|r" para mandar mandar los miembros muertos del grupo a recuperar los cadáveres.]=]
L.Follow/Follow_Info = "Responde a los comandos de seguiente por los miembros de confianza del grupo."
L.Follow/FollowingYouStart = "%s te está siguiendo."
L.Follow/FollowingYouStop = "%s dejó de seguirte."
L.Follow/FollowMe = "¡Sígueme!"
L.Follow/FollowMe_Info = "Asignar una tecla para mandar los miembres cercanos del grupo a seguirte."
L.Follow/FollowTarget = "Seguir objetivo"
L.Follow/FollowTarget_Info = "Asignar una tecla para seguir el objetivo actual."
L.Follow/FollowTooFar = "%s está demasiado lejos para seguir!"
L.Follow/RefollowAfterCombat = "Resuigir después de combate"
L.Follow/RefollowAfterCombat_Info = "Automáticamente tratará seguir el objetivo seguido previamente cuando termina el combate."
L.Follow/Reincarnate = "Reencarnarse"
L.Follow/ReleaseCorpse = "Liberar el espíritu"
L.Follow/ReleaseCorpse_Info = "Asignar una tecla para mandar los miembros muertos del grupo a liberar los espíritus."
L.Follow/SlashCorpse = "/cadaver"
L.Follow/SlashFollowMe = "/sigueme"
L.Follow/TargetedFollowMe = "Enviar /sigueme al objetivo"
L.Follow/TargetedFollowMe_Info = "Si el objetivo actual es un miembro de confianza del grupo, el comando se enviará sólo a ese personaje, en lugar del grupo entero."
L.Follow/UseSoulstone = "Usa Piedra de alma"
L.Group/CantInviteNotLeader = "No te puedo invitar, porque no estoy el líder del grupo."
L.Group/CantInviteNotTrusted = "No te puedo invitar, porque no estás en mi lista de confianza."
L.Group/CantPromoteNotLeader = "No te puedo promover, porque no estoy el líder del grupo."
L.Group/CantPromoteNotTrusted = "No te puedo promover, porque no estás en mi lista de confianza."
L.Group/CmdNoPromote = "[Nn][Oo][Pp][Rr][Oo][Mm][Oo][Vv][Ee][Rr]?"
L.Group/Group = "Grupo"
L.Group/GroupHelpText = [=[Escribe "|cffffffff/invitarme|r" para solictar una invitación de grupo de tu objetivo.

Escribe "|cffffffff/invitarme Nombre|r" para solictar una invitación de grupo del personaje "Nombre".

Escribe "|cffffffff/promoverme|r" mientras estás en el grupo para solicitar una promoción al líder del grupo.]=]
L.Group/Group_Info = "Responde a los comandos de invitar o promover de los jugadores de confianza."
L.Group/SlashInviteMe = "/invitarme"
L.Group/SlashPromoteMe = "/promoverme"
L.Loot/Loot = "Botín"
L.Loot/Loot_Info = "Cambiar automáticamente el método de despojo al modo libre en grupos confianzos."
L.Mount/Dismount = "Desmontar juntos"
L.Mount/Dismount_Info = "Desmontar cuando desmonta un miembro de confianza del grupo."
L.Mount/Mount = "Montura"
L.Mount/Mount_Info = "Montar y desmontar como un grupo."
L.Mount/MountMissing = "¡%s no tiene una montura equivalente!"
L.Mount/MountRandom = "Monturas aleatorias"
L.Mount/MountRandom_Info = [=[Al montar automáticamente, utilizar una montura aleatoria del mismo tipo del miembro de confianza del grupo.
Si está desactivada, vas a utilizar la misma monutra si lo tienen, o el equivalente primero a encontrar.]=]
L.Mount/MountTogether = "Montar juntos"
L.Mount/MountTogether_Info = "Montar cuando desmonta un miembro de confianza del grupo."
L.Quest/AbandonQuests = "Abandonar las misiones"
L.Quest/AbandonQuests_Info = "Abandonar las misiones que se abandonaron por otros miembros de confianza del grupo."
L.Quest/AcceptQuests = "Aceptar las misiones"
L.Quest/AcceptQuests_Info = "Aceptar todos las misiones."
L.Quest/OnlySharedQuests = "Sólo las misiones compartidos"
L.Quest/OnlySharedQuests_Info = "Aceptar sólo las misiones que se compartieron por otros miembros del grupo, las misiones de escoltar que se iniciaron por otros miembros del grupo, y las misiones de PNJs que ya han compartido por los miembres de confianza del grupo."
L.Quest/Quest = "Misión"
L.Quest/QuestAbandoned = "%1$s abandonó %2$s."
L.Quest/QuestAccepted = "%1$s aceptó %2$s."
L.Quest/QuestHelpText = "Si desea una lista en la pantalla de los estados de las misiones de los miembros del grupo, te recomiendo el addon Quecho, por Tekkub."
L.Quest/Quest_Info = "Ayuda a mantener en sincronía las misiones de las miembros del grupo."
L.Quest/QuestNotShareable = "Esta misión no se puede compartir."
L.Quest/QuestTurnedIn = "%1$s entregó %2$s."
L.Quest/ShareQuests = "Compartir las misiones"
L.Quest/ShareQuests_Info = "Compartir las misiones que lo aceptaron de PNJs."
L.Quest/TurnInQuests = "Entregar las misiones"
L.Quest/TurnInQuests_Info = "Entregar a PNJs las misiones completadas."
L.Taxi/SlashClearTaxi = "/borrartaxi"
L.Taxi/Taxi = "Taxi"
L.Taxi/TaxiCleared = "El destino compartido de taxi ha sido borrada."
L.Taxi/TaxiHelpText = [=[Pulse la tecla Mayús cuando hablas con un maestro de vuelo para ignorar el destino seleccionado compartido.

Escribe "|cffffffff/borrartaxi|r" para borrar el destino compardito antes de que el tiempo de espera se alcance.]=]
L.Taxi/Taxi_Info = "Seleccionar el mismo destino de taxi que los otros miembros del grupo."
L.Taxi/TaxiMismatchError = "%s: El destino no coincide."
L.Taxi/TaxiSet = "%1$s estableció el destino compartido a %2$s."
L.Taxi/TaxiTimeoutError = "%s: Se ha alcanzado el tiempo de espera para el taxi."
L.Taxi/TaxiTimeout_Info = "Borrar la selección del destino compartido después de estos segundos."

return end

------------------------------------------------------------------------
-- French
------------------------------------------------------------------------

if CURRENT_LOCALE == "frFR" then

L.Hydra_Notes = "Aide au leveling en multibox."
L.Automation/AcceptCombatRes = "...de combat"
L.Automation/AcceptCombatRes_Info = "Accepter les résurrection de combat."
L.Automation/AcceptedRes = "Accepter une résurrection de %s."
L.Automation/AcceptedSummon = "Accepter une invocation de %1$s vers %2$s."
L.Automation/AcceptedSummonCombat = "Accepter une invocation à la fin du combat..."
L.Automation/AcceptRes = "Accepte les résurrections"
L.Automation/AcceptSummons = "Accepte les invocations"
L.Automation/Automation = "Automatisation"
L.Automation/Automation_Info = "Automatise certaines tâches répétitives, comme cliquer sur les dialogues communs."
L.Automation/DeclineArenas = "Décliner les équipes d'arêne"
L.Automation/DeclinedArena = "Décliner une invitation dans une équipe d'arêne de %s."
L.Automation/DeclinedArenaPetition = "Décliner une signature de charte d'équipe d'arêne de %s."
L.Automation/DeclinedDuel = "Décliner une demande de duel de %s."
L.Automation/DeclinedGuild = "Décliner une invitation de guilde de %s."
L.Automation/DeclinedGuildPetition = "Décliner une signature de charte de guilde de %s."
L.Automation/DeclineDuels = "Décliner les duels"
L.Automation/DeclineGuilds = "Décliner les guildages"
L.Automation/NoRepairMoney = "Fonds insuffisants pour réparer !"
L.Automation/NoRepairMoneyGuild = "Fonds de banque de guilde insuffisants pour réparer !"
L.Automation/Repair = "Réparer l'équipement"
L.Automation/Repaired = "Tous les items réparés pour %s."
L.Automation/RepairedGuild = "Tous les items réparés avec les fonds de la banque de guilde pour %s."
L.Automation/RepairGuild = "Utiliser l'or de guilde"
L.Automation/RepairGuild_Info = "Payer les réparations avec la banque de guilde quand possible."
L.Automation/SellJunk = "Vendre les objets gris"
L.Automation/SoldJunk = "Vendu %1$d junk |4item:items; pour %2$s."
L.Chat/AppFocus = "Application de la focalisation"
L.Chat/Chat = "Discussion"
L.Chat/ChatHelpText = [=[Ecrivez un message dans le canal de groupe pour répondre au dernier message chuchotté transféré de n'importe quel personne.

Ecrivez "|cffffffff@name Votre message ici|r" dans un chuchotement à un personnage pour ordonner à ce personnage d'envoyer en chuchotement le message à "name".]=]
L.Chat/Chat_Info = "Transférer les chuchotements au personnage inactif vers le canal de groupe, et transférer les réponses à l'envoyeur original."
L.Chat/DetectionMethod = "Mode"
L.Chat/GroupLeader = "Chef du groupe"
L.Chat/GroupTimeoutError = "Délai de groupage expiré !"
L.Chat/WhisperFrom = "%1$s received a whisper from %2$s."
L.Chat/WhisperFromBnet = [=[%1$s a reçu un chuchotement Battle.net de %2$s :
%3$s]=]
L.Chat/WhisperFromConvo = [=[%1$s a reçu un chuchotement de %2$s :
%3$s]=]
L.Chat/WhisperFromGM = "%s a reçu un message d'un GM !"
L.Chat/WhisperTimeoutError = "Délai de chuchotement expirée !"
L.Core/AddGroup = "Ajouter le groupe"
L.Core/AddGroup_Info = "Ajouter tous les personnages de votre groupe actuel à votre liste de confiance."
L.Core/AddName = "Ajouter le nom"
L.Core/AddName_Info = "Ajouter un nom à votre liste de confiance."
L.Core/ClickForOptions = "Click for options."
L.Core/CoreHelpText = [=[Hydra fonctionne sur la base de la "confiance". Vous lui dites à quels personnages faire confiance, qu'ils soient vos personnages de multibox ou des compagnons de quête, et les fonctionnalités sont activées ou désactivées selon que vous êtes dans un groupe avec des personnages de confiance ou pas.

Par exemple, les chuchotement sont seulement transférés dans le canal de groupe si tout le monde dans votre groupe est dans votre liste de confiance.]=]
L.Core/Enable_Info = "Activer ce module."
L.Core/Hydra_Info = "Hydra est une aide au leveling en multibox dont le but est de minimiser le besoin de contrôler activement les personnages secondaires."
L.Core/RemoveName = "Supprimer le nom"
L.Core/RemoveName_Info = "Supprime un nom de votre liste de confiance."
L.Core/Timeout = "Délai"
L.Core/Verbose = "Mode verbose"
L.Core/Verbose_Info = "Activer les messages de notification de ce module."
L.Follow/AcceptCorpse = "Ressuciter"
L.Follow/CmdAccept = "accepter"
L.Follow/CmdRelease = "lib[ée]rer"
L.Follow/Follow = "Suivre"
L.Follow/FollowHelpText = [=[Tapez "|cffffffff/suivezmoi|r" pour demander à tous les membres du groupe à proximité de vous suivre.

Tapez "|cffffffff/corps libérer|r" pour demander à tous les membres du groupe mort de libérer l'esprit.

Tapez "|cffffffff/corps accepter|r" pour demander à tous les membres du groupe en fantôme d'accepter la résurrection.]=]
L.Follow/Follow_Info = "Répondre aux requêtes de suivi des membres du groupe de confiance."
L.Follow/FollowingYouStart = "%s vous suit à présent."
L.Follow/FollowingYouStop = "%s ne vous suit plus."
L.Follow/FollowMe = "Suivez-moi"
L.Follow/FollowTarget = "Suivre la cible"
L.Follow/FollowTooFar = "%s est trop loin pour vous suivre !"
L.Follow/Reincarnate = "Réincarnation"
L.Follow/ReleaseCorpse = "Libérer l'esprit"
L.Follow/SlashCorpse = "/corps"
L.Follow/SlashFollowMe = "/suivezmoi"
L.Follow/UseSoulstone = "Utiliser une pierre d'âme"
L.Group/CantInviteNotLeader = "Je ne peux pas vous inviter, car je ne suis pas le chef du groupe."
L.Group/CantInviteNotTrusted = "Je ne peux pas vous inviter, car vous n'êtes pas dans ma liste de confiance."
L.Group/CantPromoteNotLeader = "Je ne peux pas vous promouvoir, car je ne suis pas le chef du groupe."
L.Group/CantPromoteNotTrusted = "Je ne peux pas vous promouvoir, car vous n'êtes pas dans ma liste de confiance."
L.Group/CmdNoPromote = "[Nn][Oo][Pp][Rr][Oo][Mm][Oo][Uu][Vv][Oo][Ii][Rr]"
L.Group/Group = "Groupe"
L.Group/GroupHelpText = [=[Tapez "|cffffffff/invitezmoi|r" pour demander un groupage à votre cible actuelle.

Tapez "|cffffffff/invitezmoi Nom|r" pour demander un groupage à "Nom".

Tapez "|cffffffff/promouvezmoi|r" en étant groupé pour demander une promotion comme chef du groupe.]=]
L.Group/Group_Info = "Répond aux invitations et requêtes des joueurs de confiance."
L.Group/SlashInviteMe = "/invitezmoi"
L.Group/SlashPromoteMe = "/promouvezmoi"
L.Mount/Mount = "Monture"
L.Mount/MountMissing = "%s ne connaît pas cette monture !"
L.Mount/MountTogether = "Monture"
L.Mount/MountTogether_Info = "Invoque votre monture quand un autre membre du goupe invoque la sienne."
L.Quest/AbandonQuests = "Abandonner les quêtes"
L.Quest/AbandonQuests_Info = "Abandonner les quêtes abandonnées par un membre du groupe de confiance."
L.Quest/AcceptQuests = "Accepter les quêtes"
L.Quest/OnlySharedQuests_Info = "Accepter les quêtes partagées par les membres du groupe, quêtes de PNJ que les autres membres du groupe ont déjà accepté, et quête type escorte commencées par un autre membre du groupe."
L.Quest/Quest = "Quête"
L.Quest/QuestAbandoned = "%1$s a abandonné %2$s."
L.Quest/QuestAccepted = "%1$s a accepté %2$s."
L.Quest/Quest_Info = "Permet de garder les quêtes des membres du groupe synchronisées."
L.Quest/QuestNotShareable = "Cette quête ne peux pas être partagée."
L.Quest/QuestTurnedIn = "%1$s a validé %2$s."
L.Quest/ShareQuests = "Partager les quêtes"
L.Quest/ShareQuests_Info = "Partage les quêtes que vous avez acceptées des PnJ."
L.Quest/TurnInQuests = "Valider les quêtes"
L.Quest/TurnInQuests_Info = "Valider les quêtes achevées."
L.Taxi/SlashClearTaxi = "/effacertaxi"
L.Taxi/Taxi = "Taxi"
L.Taxi/TaxiCleared = "Taxi du groupe effacé."
L.Taxi/TaxiHelpText = [=[Garder la touche Maj appuyée en parlant au maître de vol pour désactiver temporairement la sélection automatique.

Tapez "|cffffffff/effacertaxi" pour effacer la sélection de trajet du groupe avant la fin du délai.]=]
L.Taxi/Taxi_Info = "Sélectionne la même destination de taxi que les autres membre du groupe."
L.Taxi/TaxiMismatchError = "%s : noeud de taxi inadéquat."
L.Taxi/TaxiSet = "%1$s a défini le taxi du groupe sur %2$s."
L.Taxi/TaxiTimeoutError = "%s : délai de taxi expiré."
L.Taxi/TaxiTimeout_Info = "Effacer la sélection de taxi après ce nombre de secondes."

return end

------------------------------------------------------------------------
-- Italian
------------------------------------------------------------------------

if CURRENT_LOCALE == "itIT" then

return end

------------------------------------------------------------------------
-- Brazilian Portuguese
------------------------------------------------------------------------

if CURRENT_LOCALE == "ptBR" then

return end

------------------------------------------------------------------------
-- Russian
------------------------------------------------------------------------

if CURRENT_LOCALE == "ruRU" then

L.Hydra_Notes = "Помощник для multibox."
L.Automation/AcceptCombatRes = "Принимать воскрешения в бою"
L.Automation/AcceptCombatRes_Info = "Принимать воскрешение в бою от всех членов группы. "
L.Automation/AcceptedRes = "Принял воскрешение от %s."
L.Automation/AcceptedSummon = "Принимаю призыв от %1$s в %2$s."
L.Automation/AcceptedSummonCombat = "Принимаю призыв когда кончится битва..."
L.Automation/AcceptRes = "Принимать воскрешения(вне боя)"
L.Automation/AcceptRes_Info = "Принять воскрешение вне боя от всех членов группы."
L.Automation/AcceptSummons = "Принимать призывы"
L.Automation/Automation = "Автоматизация"
L.Automation/Automation_Info = "Автоматизация простых повторяемых заданий, таких как нажатие на стандартные диалоги."
L.Automation/DeclineArenas = "Отказываться от приглашений в арена-команды"
L.Automation/DeclinedArena = "Отказался от приглашения в команду арены от %s."
L.Automation/DeclinedArenaPetition = "Отказался от регистрационной подписи команды арены от %s."
L.Automation/DeclinedDuel = "Отказался от дуэли с %s."
L.Automation/DeclinedGuild = "Отказался от приглашения в гильдию от %s."
L.Automation/DeclinedGuildPetition = "Отказался от регистрационной подписи гильдии от %s."
L.Automation/DeclineDuels = "Отказываться от дуэлей"
L.Automation/DeclineGuilds = "Отказываться от приглашений в гильдию"
L.Automation/NoRepairMoney = "Недостаточно средств для починки!"
L.Automation/NoRepairMoneyGuild = "Недостаточно средств гильдии для починки!"
L.Automation/Repair = "Починить снаряжение"
L.Automation/Repaired = "Починил все снаряжение на %s."
L.Automation/RepairedGuild = "Починил все снаряжение за счет гильдии на %s."
L.Automation/RepairGuild = "Использовать гильдейские средства"
L.Automation/RepairGuild_Info = "Оплачивать починку из банка гильдии (если это возможно)"
L.Automation/SellJunk = "Продать серые вещи(мусор)"
L.Automation/SummonExpired = "Призыв истек!"
L.Chat/Chat = "Чат"
L.Chat/Chat_Info = "Перенаправляет шепот, посланный неактивным персонажам в чат группы и перенаправляет ответы оригинальному отправителю."
L.Chat/DetectionMethod = "Метод обнаружения"
L.Chat/GroupLeader = "Лидер группы"
L.Chat/WhisperFrom = "%1$s получил шепот от %2$s."
L.Chat/WhisperFromBnet = [=[%1$s получил Battle.net шепот от %2$s:
%3$s]=]
L.Chat/WhisperFromGM = "%s получил шепот от ГМа!"
L.Core/AddedTrusted = "%s был добавлен в список доверенных имен."
L.Core/AddGroup = "Добавить группу"
L.Core/AddGroup_Info = "Добавить всех персонажей текущей группы в список доверенных имен."
L.Core/AddName = "Добавить имя"
L.Core/AddName_Info = "Добавить имя в список доверенных имен."
L.Core/ClickForOptions = "Нажмите на опцию"
L.Core/Enable_Info = "Включить этот модуль."
L.Core/Hydra_Info = "Hydra - это помощник для multibox, который направлен для минимизации действий, требуемых для контроля вторичных персонажей."
L.Core/RemoveAll = "Удалить все"
L.Core/RemoveAll_Info = "Удалить все имена из списка доверенных имен."
L.Core/RemovedTrusted = "%s был удален из списка доверенных имен."
L.Core/RemoveName = "Удалить имя"
L.Core/RemoveName_Info = "Удалить имя из списка доверенных имен."
L.Core/Timeout = "Просрочка"
L.Core/Verbose = "Подробном режиме"
L.Core/Verbose_Info = "Включить сообщения оповещения от этого модуля."
L.Follow/Follow = "Следить"
L.Follow/FollowingYouStart = "%s следует за вами."
L.Follow/FollowingYouStop = "%s больше не следует за вами."
L.Follow/FollowTooFar = "%s слишком далеко, чтобы следовать!"
L.Follow/Reincarnate = "Модуль Перевоплощения"
L.Group/Group = "Группа"
L.Mount/Mount = "Транспорт"
L.Quest/AbandonQuests = "Отказываться от заданий"
L.Quest/AbandonQuests_Info = "Отказываться от заданий, которые были брошены доверенным членом группы."
L.Quest/Quest = "Задание"
L.Quest/QuestNotShareable = "Этим заданием невозможно поделиться."
L.Quest/ShareQuests = "Делиться заданиями"
L.Quest/ShareQuests_Info = "Делиться заданиями, полученными от NPCs."
L.Quest/TurnInQuests = "Сдавать задания"
L.Quest/TurnInQuests_Info = "Сдавать завершенные задания."
L.Taxi/Taxi = "Модуль Такси"

return end

------------------------------------------------------------------------
-- Korean
------------------------------------------------------------------------

if CURRENT_LOCALE == "koKR" then

L.Hydra_Notes = "멀티박스 레벨링 도우미입니다."
L.Automation/AcceptCombatRes = "전투중 부할 수락"
L.Automation/AcceptedRes = "%s 님의 부활을 수락했습니다"
L.Automation/AcceptedSummon = "%1$s 님이 %2$s|1로;으로; 소환하는 것을 수락합니다."
L.Automation/AcceptedSummonCombat = "전투가 종료가 되면 소환을 수락합니다..."
L.Automation/AcceptRes = "부활 수락"
L.Automation/AcceptSummons = "소환 수락"
L.Automation/Automation = "자동 조작"
L.Automation/Automation_Info = "일반적인 대화 상자를 클릭하는 것과 같은 단순 반복적인 작업들을 자동화합니다."
L.Automation/DeclineArenas = "투기장 팀 초대 거절"
L.Automation/DeclinedArena = "%s 님의 투기장 팀 초대를 거절했습니다."
L.Automation/DeclinedArenaPetition = "%s 님의 투기장 창단 서명 요청을 거절했습니다."
L.Automation/DeclinedDuel = "%s 님의 결투 신청을 거절했습니다."
L.Automation/DeclinedGuild = "%s 님의 길드 초대를 거절했습니다."
L.Automation/DeclinedGuildPetition = "%s 님의 길드 창단 서명 요청을 거절했습니다."
L.Automation/DeclineDuels = "결투 거절"
L.Automation/DeclineGuilds = "길드 초대 거절"
L.Automation/NoRepairMoney = "수리하기 위한 금액이 부족합니다!"
L.Automation/NoRepairMoneyGuild = "수리하기 위한 길드 은행의 금액이 부족합니다!"
L.Automation/Repair = "장비 수리"
L.Automation/Repaired = "모든 아이템을 %s로 수리했습니다."
L.Automation/RepairedGuild = "모든 아이템을 길드 은행의 금액으로 수리했습니다."
L.Automation/SellJunk = "잡동사니 팔기"
L.Automation/SoldJunk = "잡동사니 아이템 %1$d개를 상인에게 판매하여 %2$s를 획득했습니다."
L.Automation/SummonExpired = "소환이 만료되었습니다!"
L.Chat/AppFocus = "애플리케이션 포커스"
L.Chat/Chat = "대화"
L.Chat/Chat_Info = "비활동 캐릭터에게 보내진 귓속말을 파티 대화로 전달하며, 귓속말을 보낸 이에게 답장을 전달합니다."
L.Chat/DetectionMethod = "모드"
L.Chat/GroupLeader = "파티장"
L.Chat/WhisperFrom = "%1$s 님이 %2$s 님으로 부터 귓속말을 받았습니다."
L.Chat/WhisperFromBnet = [=[%1$s 님이 %2$s 님으로 부터 Battle.net 귓속말을 받았습니다:
%3$s]=]
L.Chat/WhisperFromGM = "%s 님이 GM에게 귓속말을 받았습니다!"
L.Core/AddedTrusted = "%s 님을 신뢰하는 목록에 추가했습니다."
L.Core/AddGroup = "현재 파티 추가"
L.Core/AddGroup_Info = "현재 파티 그룹의 모든 캐릭터들을 신뢰하는 목록에 추가합니다."
L.Core/AddName = "이름 추가"
L.Core/AddName_Info = "신뢰하는 목록에 이름을 추가합니다."
L.Core/Hydra_Info = "Hydra는 두번째 캐릭터를 직접 조종하는 것을 최소화하는 것에 초점을 맞춘 멀티박스 레벨링 도우미입니다."
L.Core/RemovedTrusted = "%s 님을 신뢰하는 목록에서 제거했습니다."
L.Core/RemoveName = "이름 제거"
L.Core/RemoveName_Info = "신뢰하는 목록에서 이름을 제거합니다."
L.Core/Timeout = "시간 초과"
L.Core/Verbose = "수다 모드"
L.Follow/CmdAccept = "수락"
L.Follow/CmdRelease = "무덤"
L.Follow/Follow = "따라가기"
L.Follow/Follow_Info = "신뢰하는 파티원의 따라다니기 요청에 대하여 응답합니다."
L.Follow/FollowingYouStart = "%s 님이 당신을 따라다닙니다."
L.Follow/FollowingYouStop = "%s 님은 더 이상 당신을 따라다니지 않습니다."
L.Follow/FollowTooFar = "%s 님은 따라다니기엔 너무 멀리 있습니다!"
L.Follow/SlashCorpse = "/시체"
L.Follow/SlashFollowMe = "/따라와"
L.Group/CantInviteNotLeader = "저는 모듈 리더가 아니므로 당신을 초대할 수 없습니다."
L.Group/CantInviteNotTrusted = "나의 신뢰하는 목록에 존재하지 않으므로 당신을 초대할 수 없습니다."
L.Group/CantPromoteNotLeader = "저는 파티장이 아니므로 당신을 승급할 수 없습니다."
L.Group/CantPromoteNotTrusted = "나의 신뢰하는 목록에 존재하지 않으므로 때문에 당신을 승급할 수 없습니다."
L.Group/Group = "파티"
L.Group/Group_Info = "신뢰하는 파티원의 초대와 승급 요청에 대하여 응답합니다."
L.Group/SlashInviteMe = "/나초대"
L.Group/SlashPromoteMe = "/승급"
L.Mount/Mount = "탈것"
L.Mount/MountMissing = "%s 님은 탈 것이 없습니다!"
L.Mount/MountTogether = "탈것"
L.Mount/MountTogether_Info = "다른 파티원이 탈것을 소환할 때, 당신의 탈것을 소환합니다."
L.Quest/AbandonQuests = "퀘스트 포기"
L.Quest/AbandonQuests_Info = "신뢰하는 파티원이 포기한 퀘스트를 포기합니다."
L.Quest/AcceptQuests = "퀘스트 수락"
L.Quest/OnlySharedQuests_Info = "다른 파티원이 이미 NPC에게 수락했던 퀘스트와, 다른 파티원에 의해 호위 형태의 퀘스트가 시작되면, 파티원에 의하여 공유된 퀘스트를 수락합니다."
L.Quest/Quest = "퀘스트"
L.Quest/QuestAbandoned = "%1$s 님이 %2$s|1을;를; 포기했습니다."
L.Quest/QuestAccepted = "%1$s 님이 %2$s|1을;를; 수락했습니다."
L.Quest/Quest_Info = "파티원의 퀘스트와 항상 동기화하도록 도와줍니다."
L.Quest/QuestNotShareable = "해당 퀘스트는 공유할 수 없습니다."
L.Quest/QuestTurnedIn = "%1$s 님이 %2$s|1을;를; 반환했습니다."
L.Quest/ShareQuests = "퀘스트 공유"
L.Quest/ShareQuests_Info = "NPC에게 수락한 퀘스트를 공유합니다."
L.Quest/TurnInQuests = "퀘스트 제출"
L.Quest/TurnInQuests_Info = "완료한 퀘스트를 제출합니다."
L.Taxi/SlashClearTaxi = "/택시지우기"
L.Taxi/Taxi = "택시"
L.Taxi/TaxiCleared = "파티 택시가 지워졌습니다."
L.Taxi/Taxi_Info = "택시(그리핀, 와이번)의 목적지를 다른 파티원과 동일한 곳으로 선택합니다."
L.Taxi/TaxiMismatchError = "%s: 님의 택시 노드가 일치하지 않습니다."
L.Taxi/TaxiSet = "%1$s 님이 지정한 파티 택시의 노드 %2$s."
L.Taxi/TaxiTimeoutError = "%s: 님의 택시가 시간 초과되었습니다."
L.Taxi/TaxiTimeout_Info = "이 시간(초)이 경과된 후에 택시 선택을 지웁니다."

return end

------------------------------------------------------------------------
-- Simplified Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhCN" then

return end

------------------------------------------------------------------------
-- Traditional Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhTW" then

return end
